import { useNavigate } from 'react-router-dom'
import { ArrowUpRight, Pause, Play, Zap, ZapOff } from 'lucide-react'
import { useAppData } from '../App'
import { EmptyState, ErrorState, StatusBadge } from '../components/ui'
import { date, instrument, money, signedMoney, time } from '../lib/format'

export function DashboardPage() {
  const { positions, signals, trades, status, settings, requestAction, openPosition, openSignal } = useAppData()
  const navigate = useNavigate()
  const closed = trades.filter(t => t.closedAt.slice(0, 10) === status.sessionDate)
  const realized = closed.reduce((sum, t) => sum + t.realizedPnL, 0)
  const openPnl = positions.reduce((sum, p) => sum + p.unrealizedPnL, 0)
  const deployed = positions.reduce((sum, p) => sum + p.averageEntry * p.quantity, 0)
  const used = Math.round(deployed / Math.max(1, settings.maxCapitalDeployed) * 100)
  const attention = signals.filter(s => ['MANUAL_REVIEW', 'REJECTED'].includes(s.outcome)).sort((a, b) => b.receivedAt.localeCompare(a.receivedAt))
  const waiting = signals.filter(s => s.outcome === 'WAITING')
  const unhealthy = !status.backendAvailable || [status.broker.state, status.telegram.state, status.marketData.state].some(s => s !== 'CONNECTED')
  return <div className="studio-desk">
    {unhealthy && <ErrorState title="Connection issue" description="Check system logs before relying on live status." />}
    <section className="session-overview" aria-label="Session results">
      <div className="session-result"><span className="eyebrow">SESSION P&L <span className="session-mode">{status.mode === 'PAPER' ? 'Paper trading' : 'Live trading'}</span></span><strong className={`session-total ${realized + openPnl >= 0 ? 'positive' : 'negative'}`}>{signedMoney(realized + openPnl)}</strong><div className="result-breakdown"><div><span>Realized</span><strong>{signedMoney(realized)}</strong></div><div><span>Unrealized</span><strong>{signedMoney(openPnl)}</strong></div><div><span>Closed trades</span><strong>{closed.length}</strong></div></div></div>
      <div className="capital-summary"><div className="capital-ring" style={{ background: `conic-gradient(var(--accent) ${Math.min(100, used)}%, var(--accent-track) 0)` }}><span>{used}<small>%</small></span></div><div><span className="eyebrow">CAPITAL DEPLOYED</span><strong>{money(deployed, 0)}</strong><small>of {money(settings.maxCapitalDeployed, 0)} limit</small><button className="text-action" onClick={() => navigate('/settings')}>Manage limits <ArrowUpRight size={14} /></button></div></div>
    </section>
    <section className="control-strip" aria-label="System status"><div className="monitor-state"><i className={unhealthy || !status.tradingEnabled ? 'paused' : ''} /><strong>{status.emergencyStopped ? 'Emergency stop active' : unhealthy ? 'Connection issue' : status.tradingEnabled ? 'Monitoring signals' : 'Entries paused'}</strong></div><div className="connection-chips">{[['Broker', status.broker.state], ['Telegram', status.telegram.state], ['Prices', status.marketData.state]].map(([name, state]) => <span key={name} title={`${name}: ${state.toLowerCase()}`}><i className={state.toLowerCase()} />{name}</span>)}</div><div className="control-buttons"><button onClick={() => requestAction(status.tradingEnabled ? 'PAUSE_NEW_TRADES' : 'RESUME_NEW_TRADES')}>{status.tradingEnabled ? <Pause size={14} /> : <Play size={14} />}{status.tradingEnabled ? 'Pause entries' : 'Resume entries'}</button><button onClick={() => requestAction(status.autoExecutionEnabled ? 'DISABLE_AUTO_EXECUTION' : 'ENABLE_AUTO_EXECUTION')}>{status.autoExecutionEnabled ? <ZapOff size={14} /> : <Zap size={14} />}{status.autoExecutionEnabled ? 'Disable auto' : 'Enable auto'}</button></div></section>
    <div className="desk-section-heading"><h2>In the market <span>{positions.length}</span></h2><button className="text-action" onClick={() => navigate('/positions')}>All positions <ArrowUpRight size={16} /></button></div>
    <section className="position-cards" aria-label="Open positions">{positions.map(p => <button key={p.id} className="position-tile" onClick={() => openPosition(p)}><div className="position-title"><span className={`contract-stamp ${p.optionType.toLowerCase()}`}>{p.underlying.slice(0, 2)}</span><div><h3>{p.underlying} <span>{p.strike} {p.optionType}</span></h3><small>{date(p.expiry)} · {p.lots} {p.lots === 1 ? 'lot' : 'lots'} · {p.quantity} qty</small></div><ArrowUpRight size={19} /></div><div className="position-return"><strong className={p.unrealizedPnL >= 0 ? 'positive' : 'negative'}>{signedMoney(p.unrealizedPnL)}</strong><span className={p.unrealizedPnL >= 0 ? 'positive' : 'negative'}>{p.ltp >= p.averageEntry ? '+' : ''}{((p.ltp / p.averageEntry - 1) * 100).toFixed(2)}%</span></div><div className="position-prices"><div><span>Entry</span><strong>{money(p.averageEntry)}</strong></div><div><span>Last price</span><strong>{money(p.ltp)}</strong></div><div><span>Stop loss</span><strong>{money(p.stopLoss)}</strong></div><div><span>Target</span><strong>{money(p.targetMin)}</strong></div></div></button>)}{!positions.length && <EmptyState title="No open positions" description="New positions will appear here." />}</section>
    <div className="desk-lower"><section className="waiting-panel"><div className="desk-section-heading"><h2>Next in line <span>{waiting.length}</span></h2><button className="text-action" onClick={() => navigate('/signals')}>All signals <ArrowUpRight size={16} /></button></div><div className="waiting-list">{waiting.map(s => <button key={s.id} className="waiting-item" onClick={() => openSignal(s)}><div><strong>{instrument(s)}</strong><small>{time(s.receivedAt)} IST · Entry {s.entryType.toLowerCase()} {money(s.entryPrice)}</small></div><div className="waiting-price"><strong>{s.ltp == null ? '—' : money(s.ltp)}</strong><StatusBadge status="WAITING" /></div><ArrowUpRight size={16} /></button>)}{!waiting.length && <EmptyState title="Queue clear" description="No signals waiting for entry." />}</div></section><section className="review-panel"><div className="desk-section-heading"><h2>Needs a look <span>{attention.length}</span></h2></div>{attention.map(s => <button key={s.id} className="review-item" onClick={() => openSignal(s)}><div><StatusBadge status={s.outcome} text={s.outcome === 'MANUAL_REVIEW' ? 'Review' : 'Rejected'} /><ArrowUpRight size={16} /></div><strong>{instrument(s)}</strong><p>{s.rejectionReason}</p></button>)}</section></div>
  </div>
}

