import { useEffect, useState } from 'react'
import { LockKeyhole, RotateCcw, Save, ShieldCheck } from 'lucide-react'
import { useAppData } from '../App'
import { ConfirmationModal, SectionTitle } from '../components/ui'
import type { TradingSettings } from '../types'

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  return <label className="setting-field"><span>{label}</span>{hint && <small>{hint}</small>}{children}</label>
}

function Toggle({ label, hint, checked, onChange }: { label: string; hint?: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <label className="setting-toggle"><span><strong>{label}</strong>{hint && <small>{hint}</small>}</span><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} /><i /></label>
}

export function SettingsPage() {
  const { settings, setSettings } = useAppData()
  const [draft, setDraft] = useState<TradingSettings>(settings)
  const [confirm, setConfirm] = useState(false)
  useEffect(() => setDraft(settings), [settings])
  const dirty = JSON.stringify(draft) !== JSON.stringify(settings)
  const valid = [draft.fixedLots, draft.capitalPerTrade, draft.maxTradesPerDay, draft.maxSimultaneousPositions, draft.maxCapitalDeployed, draft.maxDailyLoss, draft.maxSignalAgeSeconds].every(value => Number.isFinite(value) && value > 0)
    && [draft.maxEntrySlippagePercent, draft.maxEntryDistancePercent].every(value => Number.isFinite(value) && value >= 0)
    && (!draft.forceSquareOff || /^([01]\d|2[0-3]):[0-5]\d$/.test(draft.squareOffTime))
  const update = <K extends keyof TradingSettings>(key: K, value: TradingSettings[K]) => setDraft(current => ({ ...current, [key]: value }))
  return <><div className="settings-notice"><ShieldCheck size={19} /><div><strong>Rules are enforced by the trading backend</strong><p>These controls store configuration only. Changes to active trading should be reviewed before saving.</p></div><span>MOCK API</span></div><div className="settings-grid"><div className="settings-main">
    <section className="panel settings-panel"><SectionTitle title="General" subtitle="Choose the trading environment and source" /><div className="setting-fields"><Toggle label="Trading enabled" hint="Allow new trades when rules permit" checked={draft.tradingEnabled} onChange={value => update('tradingEnabled', value)} /><div className="settings-two-col"><Field label="Trading mode"><select value={draft.mode} onChange={event => update('mode', event.target.value as TradingSettings['mode'])}><option value="PAPER">Paper mode</option><option value="LIVE">Live mode</option></select></Field><Field label="Broker"><select value={draft.broker} onChange={event => update('broker', event.target.value)}><option>Angel One</option></select></Field></div><Field label="Telegram source"><select value={draft.telegramSource} onChange={event => update('telegramSource', event.target.value)}><option>Mani Telegram</option></select></Field></div></section>
    <section className="panel settings-panel"><SectionTitle title="Position sizing" subtitle="Choose one method for sizing each new trade" /><div className="setting-fields"><div className="segmented"><button className={draft.sizingMethod === 'LOTS' ? 'selected' : ''} onClick={() => update('sizingMethod', 'LOTS')}>Fixed lots</button><button className={draft.sizingMethod === 'CAPITAL' ? 'selected' : ''} onClick={() => update('sizingMethod', 'CAPITAL')}>Fixed capital</button></div>{draft.sizingMethod === 'LOTS' ? <Field label="Lots per trade"><input type="number" min="1" value={draft.fixedLots} onChange={event => update('fixedLots', Number(event.target.value))} /></Field> : <Field label="Capital per trade (₹)"><input type="number" min="1" value={draft.capitalPerTrade} onChange={event => update('capitalPerTrade', Number(event.target.value))} /></Field>}</div></section>
    <section className="panel settings-panel"><SectionTitle title="Risk controls" subtitle="Portfolio limits and signal safeguards" /><div className="setting-fields"><div className="settings-two-col"><Field label="Maximum trades / day"><input type="number" min="1" value={draft.maxTradesPerDay} onChange={event => update('maxTradesPerDay', Number(event.target.value))} /></Field><Field label="Simultaneous positions"><input type="number" min="1" value={draft.maxSimultaneousPositions} onChange={event => update('maxSimultaneousPositions', Number(event.target.value))} /></Field><Field label="Max capital deployed (₹)"><input type="number" min="1" value={draft.maxCapitalDeployed} onChange={event => update('maxCapitalDeployed', Number(event.target.value))} /></Field><Field label="Maximum daily loss (₹)"><input type="number" min="1" value={draft.maxDailyLoss} onChange={event => update('maxDailyLoss', Number(event.target.value))} /></Field><Field label="Entry slippage limit (%)"><input type="number" min="0" step="0.1" value={draft.maxEntrySlippagePercent} onChange={event => update('maxEntrySlippagePercent', Number(event.target.value))} /></Field><Field label="Maximum signal age (sec)"><input type="number" min="1" value={draft.maxSignalAgeSeconds} onChange={event => update('maxSignalAgeSeconds', Number(event.target.value))} /></Field></div><Toggle label="Reject duplicate signals" checked={draft.rejectDuplicateSignals} onChange={value => update('rejectDuplicateSignals', value)} /></div></section>
    <section className="panel settings-panel"><SectionTitle title="Entry & target rules" subtitle="Define price tolerance and exit behaviour" /><div className="setting-fields"><div className="settings-two-col"><Field label="Maximum entry distance (%)"><input type="number" min="0" step="0.1" value={draft.maxEntryDistancePercent} onChange={event => update('maxEntryDistancePercent', Number(event.target.value))} /></Field><Field label="Order preference"><select value={draft.orderType} onChange={event => update('orderType', event.target.value as TradingSettings['orderType'])}><option value="MARKET">Market order</option><option value="LIMIT">Limit order</option></select></Field></div><Toggle label="Skip when price has moved too far" checked={draft.skipMovedPrice} onChange={value => update('skipMovedPrice', value)} /><Field label="Target handling"><select value={draft.targetRule} onChange={event => update('targetRule', event.target.value as TradingSettings['targetRule'])}><option value="EXIT_FIRST">Exit all at first target</option><option value="PARTIAL_FIRST">Partial exit at first target</option><option value="HOLD_UPPER">Hold toward upper target</option><option value="FOLLOW_UPDATES">Follow Mani updates only</option></select></Field></div></section>
    <section className="panel settings-panel"><SectionTitle title="Intraday rules" subtitle="Session close and overnight exposure" /><div className="setting-fields"><Toggle label="Force square off" checked={draft.forceSquareOff} onChange={value => update('forceSquareOff', value)} /><Field label="Square-off time (IST)"><input type="time" value={draft.squareOffTime} onChange={event => update('squareOffTime', event.target.value)} disabled={!draft.forceSquareOff} /></Field><Toggle label="Allow overnight positions" checked={draft.allowOvernight} onChange={value => update('allowOvernight', value)} /></div></section>
  </div><aside className="settings-side"><div className="panel settings-help"><div className="settings-help-icon"><LockKeyhole size={20} /></div><strong>Configuration only</strong><p>The frontend passes these values to the API. The backend decides whether a signal can be executed and enforces every limit.</p><div className="settings-help-divider" /><span>Last saved configuration</span><strong>{settings.mode === 'PAPER' ? 'Paper trading' : 'Live trading'} · {settings.broker}</strong></div></aside></div><div className="settings-savebar"><span>{!valid ? 'Enter valid positive limits before saving' : dirty ? 'You have unsaved changes' : 'All changes saved'}</span><div><button className="button button-secondary" disabled={!dirty} onClick={() => setDraft(settings)}><RotateCcw size={15} /> Reset</button><button className="button button-primary" disabled={!dirty || !valid} onClick={() => setConfirm(true)}><Save size={15} /> Save trading rules</button></div></div>{confirm && <ConfirmationModal title="Save trading rules" description={`Apply these configuration changes to the ${draft.mode.toLowerCase()} trading workspace? The backend will enforce the saved rules when connected.`} confirmLabel="Save rules" onCancel={() => setConfirm(false)} onConfirm={() => { setSettings(draft); setConfirm(false) }} />}</>
}
