import { ChevronRight } from 'lucide-react'
import type { Position, Signal, Trade } from '../types'
import { date, instrument, money, shortDate, signedMoney, time } from '../lib/format'
import { StatusBadge } from './ui'

export function PositionTable({ positions, onOpen, compact = false }: { positions: Position[]; onOpen: (position: Position) => void; compact?: boolean }) {
  return <div className="table-scroll"><table className={`data-table ${compact ? 'compact-table' : ''}`}><thead><tr><th>INSTRUMENT</th><th>QTY / LOTS</th><th>AVG. ENTRY</th><th>LTP</th><th>STOP / TARGET</th><th>UNREALIZED P&L</th><th>STATUS</th><th>SOURCE SIGNAL</th><th aria-label="Details" /></tr></thead><tbody>{positions.map(position => <tr key={position.id} onClick={() => onOpen(position)} tabIndex={0} onKeyDown={event => { if (event.key === 'Enter') onOpen(position) }}><td><div className="instrument-cell"><div className={`option-mark ${position.optionType.toLowerCase()}`}>{position.optionType}</div><div><strong>{position.underlying} <span>{position.strike} {position.optionType}</span></strong><small>{shortDate(position.expiry)} expiry · Opened {time(position.openedAt)} IST</small></div></div></td><td><strong>{position.quantity}</strong><small>{position.lots} {position.lots === 1 ? 'lot' : 'lots'}</small></td><td>{money(position.averageEntry)}</td><td><strong>{money(position.ltp)}</strong></td><td><span className="price-stack">{money(position.stopLoss)} <span>/</span> {money(position.targetMin)}{position.targetMax ? `–${money(position.targetMax)}` : ''}</span></td><td><strong className={position.unrealizedPnL >= 0 ? 'positive' : 'negative'}>{signedMoney(position.unrealizedPnL)}</strong></td><td><StatusBadge status={position.status} text="Open" /></td><td><span className="order-id">{position.signalId}</span></td><td><ChevronRight size={17} className="row-chevron" /></td></tr>)}</tbody></table></div>
}

export function SignalTable({ signals, onOpen }: { signals: Signal[]; onOpen: (signal: Signal) => void }) {
  return <div className="table-scroll"><table className="data-table signals-table"><thead><tr><th>RECEIVED</th><th>SIGNAL / RAW MESSAGE</th><th>ENTRY</th><th>SL / TARGET</th><th>CONFIDENCE</th><th>LTP</th><th>RESULT</th><th aria-label="Details" /></tr></thead><tbody>{signals.map(signal => <tr key={signal.id} onClick={() => onOpen(signal)} tabIndex={0} onKeyDown={event => { if (event.key === 'Enter') onOpen(signal) }}><td><strong>{time(signal.receivedAt)}</strong><small>{shortDate(signal.receivedAt)} · IST</small></td><td className="signal-main-cell"><div className="instrument-cell"><div className={`option-mark ${signal.optionType.toLowerCase()}`}>{signal.optionType}</div><div><strong>{instrument(signal)}</strong><small>{signal.rawMessage.replaceAll('\n', ' ').slice(0, 68)}{signal.rawMessage.length > 68 ? '…' : ''}</small></div></div></td><td><strong>{money(signal.entryPrice)}</strong><small>{signal.entryType.toLowerCase()}</small></td><td><strong>{signal.stopLoss ? money(signal.stopLoss) : '—'} <span className="muted-slash">/</span> {money(signal.targetMin)}</strong><small>{signal.targetMax ? `Upper ${money(signal.targetMax)}` : 'Single target'}</small></td><td><span className={`confidence ${signal.confidence < .8 ? 'confidence-low' : ''}`}><i />{Math.round(signal.confidence * 100)}%</span></td><td>{signal.ltp == null ? '—' : money(signal.ltp)}</td><td><StatusBadge status={signal.outcome} text={signal.outcome === 'MANUAL_REVIEW' ? 'Review' : undefined} /><small className="result-detail">{signal.resultingAction}</small></td><td><ChevronRight size={17} className="row-chevron" /></td></tr>)}</tbody></table></div>
}

export function TradeTable({ trades }: { trades: Trade[] }) {
  return <div className="table-scroll"><table className="data-table"><thead><tr><th>DATE / INSTRUMENT</th><th>ENTRY</th><th>EXIT</th><th>QTY</th><th>REALIZED P&L</th><th>EXIT REASON</th><th>DURATION</th><th>ORDER IDS</th></tr></thead><tbody>{trades.map(trade => <tr key={trade.id}><td><div className="instrument-cell"><div className={`option-mark ${trade.optionType.toLowerCase()}`}>{trade.optionType}</div><div><strong>{instrument(trade)}</strong><small>{date(trade.closedAt)} · {trade.source}</small></div></div></td><td>{money(trade.entryPrice)}<small>SL {money(trade.stopLoss)}</small></td><td>{money(trade.exitPrice)}<small>Target {money(trade.targetMin)}</small></td><td>{trade.quantity}</td><td><strong className={trade.realizedPnL >= 0 ? 'positive' : 'negative'}>{signedMoney(trade.realizedPnL)}</strong></td><td><StatusBadge status={trade.exitReason === 'STOP_LOSS' ? 'REJECTED' : 'TARGET_HIT'} text={trade.exitReason.replaceAll('_', ' ')} /></td><td>{Math.round((new Date(trade.closedAt).getTime() - new Date(trade.openedAt).getTime()) / 60000)} min</td><td><span className="order-id">{trade.brokerOrderIds.join(' · ')}</span></td></tr>)}</tbody></table></div>
}
